#ifndef AVATAR_SHADER_MACROS_CGINC
#define AVATAR_SHADER_MACROS_CGINC

// Field related functions

#define SET_AVATAR_SHADER_SURFACE_FIELD(SurfaceOutputVariable, FieldName, Value) \
    SurfaceOutputVariable.FieldName = Value;

#define GET_AVATAR_SHADER_SURFACE_FIELD(SurfaceOutputVariable, FieldName) \
    SurfaceOutputVariable.FieldName

// Define some commonly used fields

// Smoothness
#define AVATAR_SHADER_SURFACE_SMOOTHNESS_FIELD_NAME Smoothness
#define AVATAR_SHADER_SURFACE_SMOOTHNESS_FIELD_DECLARATION \
    half AVATAR_SHADER_SURFACE_SMOOTHNESS_FIELD_NAME;

#define SET_AVATAR_SHADER_SURFACE_SMOOTHNESS_FIELD(SurfaceOutputVariable, Value) \
    SET_AVATAR_SHADER_SURFACE_FIELD(SurfaceOutputVariable, AVATAR_SHADER_SURFACE_SMOOTHNESS_FIELD_NAME, Value)

#define GET_AVATAR_SHADER_SURFACE_SMOOTHNESS_FIELD(SurfaceOutputVariable) \
    GET_AVATAR_SHADER_SURFACE_FIELD(SurfaceOutputVariable, AVATAR_SHADER_SURFACE_SMOOTHNESS_FIELD_NAME)

// Roughness
#define AVATAR_SHADER_SURFACE_ROUGHNESS_FIELD_NAME Roughness
#define AVATAR_SHADER_SURFACE_ROUGHNESS_FIELD_DECLARATION \
    half AVATAR_SHADER_SURFACE_ROUGHNESS_FIELD_NAME;

#define SET_AVATAR_SHADER_SURFACE_ROUGHNESS_FIELD(SurfaceOutputVariable, Value) \
    SET_AVATAR_SHADER_SURFACE_FIELD(SurfaceOutputVariable, AVATAR_SHADER_SURFACE_ROUGHNESS_FIELD_NAME, Value)

#define GET_AVATAR_SHADER_SURFACE_ROUGHNESS_FIELD(SurfaceOutputVariable) \
    GET_AVATAR_SHADER_SURFACE_FIELD(SurfaceOutputVariable, AVATAR_SHADER_SURFACE_ROUGHNESS_FIELD_NAME)

// Normal
#define AVATAR_SHADER_SURFACE_NORMAL_FIELD_NAME Normal
#define AVATAR_SHADER_SURFACE_NORMAL_FIELD_DECLARATION \
    float3 AVATAR_SHADER_SURFACE_NORMAL_FIELD_NAME;

#define SET_AVATAR_SHADER_SURFACE_NORMAL_FIELD(SurfaceOutputVariable, Value) \
    SET_AVATAR_SHADER_SURFACE_FIELD(SurfaceOutputVariable, AVATAR_SHADER_SURFACE_NORMAL_FIELD_NAME, Value)

#define GET_AVATAR_SHADER_SURFACE_NORMAL_FIELD(SurfaceOutputVariable) \
    GET_AVATAR_SHADER_SURFACE_FIELD(SurfaceOutputVariable, AVATAR_SHADER_SURFACE_NORMAL_FIELD_NAME)

// Albedo
#define AVATAR_SHADER_SURFACE_ALBEDO_FIELD_NAME Albedo
#define AVATAR_SHADER_SURFACE_ALBEDO_FIELD_DECLARATION \
    fixed3 AVATAR_SHADER_SURFACE_ALBEDO_FIELD_NAME;

#define SET_AVATAR_SHADER_SURFACE_ALBEDO_FIELD(SurfaceOutputVariable, Value) \
    SET_AVATAR_SHADER_SURFACE_FIELD(SurfaceOutputVariable, AVATAR_SHADER_SURFACE_ALBEDO_FIELD_NAME, Value)

#define GET_AVATAR_SHADER_SURFACE_ALBEDO_FIELD(SurfaceOutputVariable) \
    GET_AVATAR_SHADER_SURFACE_FIELD(SurfaceOutputVariable, AVATAR_SHADER_SURFACE_ALBEDO_FIELD_NAME)

// Metallic
#define AVATAR_SHADER_SURFACE_METALLIC_FIELD_NAME Metallic
#define AVATAR_SHADER_SURFACE_METALLIC_FIELD_DECLARATION \
    half AVATAR_SHADER_SURFACE_METALLIC_FIELD_NAME;

#define SET_AVATAR_SHADER_SURFACE_METALLIC_FIELD(SurfaceOutputVariable, Value) \
    SET_AVATAR_SHADER_SURFACE_FIELD(SurfaceOutputVariable, AVATAR_SHADER_SURFACE_METALLIC_FIELD_NAME, Value)

#define GET_AVATAR_SHADER_SURFACE_METALLIC_FIELD(SurfaceOutputVariable) \
    GET_AVATAR_SHADER_SURFACE_FIELD(SurfaceOutputVariable, AVATAR_SHADER_SURFACE_METALLIC_FIELD_NAME)

// Occlusion
#define AVATAR_SHADER_SURFACE_OCCLUSION_FIELD_NAME Occlusion
#define AVATAR_SHADER_SURFACE_OCCLUSION_FIELD_DECLARATION \
    half AVATAR_SHADER_SURFACE_OCCLUSION_FIELD_NAME;


#define SET_AVATAR_SHADER_SURFACE_OCCLUSION_FIELD(SurfaceOutputVariable, Value) \
    SET_AVATAR_SHADER_SURFACE_FIELD(SurfaceOutputVariable, AVATAR_SHADER_SURFACE_OCCLUSION_FIELD_NAME, Value)

#define GET_AVATAR_SHADER_SURFACE_OCCLUSION_FIELD(SurfaceOutputVariable) \
    GET_AVATAR_SHADER_SURFACE_FIELD(SurfaceOutputVariable, AVATAR_SHADER_SURFACE_OCCLUSION_FIELD_NAME)

// Alpha
#define AVATAR_SHADER_SURFACE_ALPHA_FIELD_NAME Alpha
#define AVATAR_SHADER_SURFACE_ALPHA_FIELD_DECLARATION \
    half AVATAR_SHADER_SURFACE_ALPHA_FIELD_NAME;

#define SET_AVATAR_SHADER_SURFACE_ALPHA_FIELD(SurfaceOutputVariable, Value) \
    SET_AVATAR_SHADER_SURFACE_FIELD(SurfaceOutputVariable, AVATAR_SHADER_SURFACE_ALPHA_FIELD_NAME, Value)

#define GET_AVATAR_SHADER_SURFACE_ALPHA_FIELD(SurfaceOutputVariable) \
    GET_AVATAR_SHADER_SURFACE_FIELD(SurfaceOutputVariable, AVATAR_SHADER_SURFACE_ALPHA_FIELD_NAME)

#endif
