#ifndef AVATAR_COMMON_SURFACE_FIELDS_CGINC
#define AVATAR_COMMON_SURFACE_FIELDS_CGINC

#include "AvatarCommonUtils.cginc"

// Min Diffuse
#define AVATAR_SHADER_SURFACE_MIN_DIFFUSE_FIELD_NAME MinDiffuse
#define AVATAR_SHADER_SURFACE_MIN_DIFFUSE_FIELD_DECLARATION \
    half AVATAR_SHADER_SURFACE_MIN_DIFFUSE_FIELD_NAME;

#define SET_AVATAR_SHADER_SURFACE_MIN_DIFFUSE_FIELD(SurfaceOutputVariable, Value) \
    SET_AVATAR_SHADER_SURFACE_FIELD(SurfaceOutputVariable, AVATAR_SHADER_SURFACE_MIN_DIFFUSE_FIELD_NAME, Value)

#define GET_AVATAR_SHADER_SURFACE_MIN_DIFFUSE_FIELD(SurfaceOutputVariable) \
    GET_AVATAR_SHADER_SURFACE_FIELD(SurfaceOutputVariable, AVATAR_SHADER_SURFACE_MIN_DIFFUSE_FIELD_NAME)

// Common surface fields across all avatar shaders
#if defined(_LIGHTING_SYSTEM_UNITY) || defined(_LIGHTING_SYSTEM_VERTEX_GI)

    #if defined(_LIGHTING_SYSTEM_UNITY)

        #include "../UnityLighting/AvatarUnitySurfaceFields.cginc"

        #define AVATAR_COMMON_SURFACE_FIELDS \
            AVATAR_SHADER_UNITY_SURFACE_REQUIRED_FIELDS \
            AVATAR_SHADER_SURFACE_MIN_DIFFUSE_FIELD_DECLARATION \
            AVATAR_SHADER_SURFACE_ROUGHNESS_FIELD_DECLARATION \
            AVATAR_SHADER_SURFACE_ALPHA_FIELD_DECLARATION

    #else

        #define AVATAR_COMMON_SURFACE_FIELDS \
            AVATAR_SHADER_SURFACE_ALBEDO_FIELD_DECLARATION \
            AVATAR_SHADER_SURFACE_NORMAL_FIELD_DECLARATION \
            AVATAR_SHADER_SURFACE_ROUGHNESS_FIELD_DECLARATION \
            AVATAR_SHADER_SURFACE_SMOOTHNESS_FIELD_DECLARATION \
            AVATAR_SHADER_SURFACE_METALLIC_FIELD_DECLARATION \
            AVATAR_SHADER_SURFACE_MIN_DIFFUSE_FIELD_DECLARATION \
            AVATAR_SHADER_SURFACE_ALPHA_FIELD_DECLARATION \
            AVATAR_SHADER_SURFACE_OCCLUSION_FIELD_DECLARATION

    #endif

    #define SET_AVATAR_SHADER_SURFACE_COMMON_FIELDS(SurfOutput, AlbedoVal, RoughVal, MetalVal, AlphaVal, OcclusionVal, MinDiffuseVal) \
        half clampedRoughness = ClampPerceptualRoughness(RoughVal); \
        SET_AVATAR_SHADER_SURFACE_ALBEDO_FIELD(SurfOutput, AlbedoVal) \
        SET_AVATAR_SHADER_SURFACE_ROUGHNESS_FIELD(SurfOutput, clampedRoughness) \
        SET_AVATAR_SHADER_SURFACE_SMOOTHNESS_FIELD(SurfOutput, 1 - clampedRoughness) \
        SET_AVATAR_SHADER_SURFACE_METALLIC_FIELD(SurfOutput, MetalVal) \
        SET_AVATAR_SHADER_SURFACE_ALPHA_FIELD(SurfOutput, AlphaVal) \
        SET_AVATAR_SHADER_SURFACE_OCCLUSION_FIELD(SurfOutput, OcclusionVal) \
        SET_AVATAR_SHADER_SURFACE_MIN_DIFFUSE_FIELD(SurfOutput, MinDiffuseVal)
#endif

#endif
