#ifndef AVATAR_UNITY_SURFACE_FIELDS_CGINC
#define AVATAR_UNITY_SURFACE_FIELDS_CGINC

#include "../AvatarCommon/AvatarShaderMacros.cginc"

// These are all fields which are required by the Unity lighting scheme, NOT ones
// that are required by different shaders.

#define AVATAR_SHADER_UNITY_SURFACE_REQUIRED_FIELDS \
    AVATAR_SHADER_SURFACE_SMOOTHNESS_FIELD_DECLARATION \
    AVATAR_SHADER_SURFACE_NORMAL_FIELD_DECLARATION \
    AVATAR_SHADER_SURFACE_ALBEDO_FIELD_DECLARATION \
    AVATAR_SHADER_SURFACE_METALLIC_FIELD_DECLARATION \
    AVATAR_SHADER_SURFACE_OCCLUSION_FIELD_DECLARATION

#endif
