#ifndef OVR_AVATAR_SUPPORT_DEFINES_INCLUDED
#define OVR_AVATAR_SUPPORT_DEFINES_INCLUDED

#if SHADER_TARGET >= 35 && (defined(SHADER_API_D3D11) || defined(SHADER_API_GLES3) || defined(SHADER_API_GLCORE) || defined(SHADER_API_VULKAN) || (defined(SHADER_API_METAL) && defined(UNITY_COMPILER_HLSLCC)))
#define OVR_SUPPORT_EXTERNAL_BUFFERS
#endif

#endif // OVR_AVATAR_SUPPORT_DEFINES_INCLUDED
